APP_NAME="kingGame"
ENV_DOCKER_API_CONTAINER="kinggame_api"
ENV_DOCKER_API_CONTAINER_PORT="9998"
ENV_DOCKER_MYSQL_CONTAINER="gamekinglife-mysql-1"
ENV_DOCKER_MYSQL_CONTAINER_PORT="3399"
ENV_DOCKER_MYSQL_DB_NAME="kinggame_mysql"
ENV_DOCKER_MYSQL_DB_USER="kingGameUser"
ENV_DOCKER_MYSQL_DB_PASS="kingGamePass"
GRADLE_EXEC = ./gradlew --info clean
DOCKER_EXEC = docker


mysqlRemove:
	@echo "Remove mysql container"
	@$(DOCKER_EXEC) rm -f -v $(ENV_DOCKER_MYSQL_CONTAINER) || true
mysqlRun: mysqlRemove
	@echo "Run mysql container"
	@$(DOCKER_EXEC) run -d -p $(ENV_DOCKER_MYSQL_CONTAINER_PORT):3306 --name $(ENV_DOCKER_MYSQL_CONTAINER) -e MYSQL_ROOT_PASSWORD=$(ENV_DOCKER_MYSQL_DB_PASS) -e MYSQL_DATABASE=$(ENV_DOCKER_MYSQL_DB_NAME) -e MYSQL_USER=$(ENV_DOCKER_MYSQL_DB_USER) -e MYSQL_PASSWORD=$(ENV_DOCKER_MYSQL_DB_PASS) mysql:5.7
	@sleep 10